# Site settings
title: Akash Kundu
email: akash.kundu@helsinki.fi
description: I.. a universe of atoms an atom in the universe.
baseurl: ""
domain: aqasch.github.io
url: https://aqasch.github.io
github_username: Aqasch
author: Akash Kundu

# Build settings
theme: jekyll-theme-minimal
# For more features, consider using remote_theme instead:
# remote_theme: vaibhavvikas/jekyll-theme-minimalistic
# plugins:
#   - jekyll-remote-theme

plugins:
  - jekyll-feed
  - jemoji # for GitHub-flavored emoji support

include:
  - font.css

# Pagination (optional, if you have a blog)
paginate: 5
paginate_path: /blog/page:num/

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Social media links (customize as needed)
social:
  github: Aqasch
  email: akash.kundu@helsinki.fi

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
